plugins {
	id "com.crystaelix.loom" version "1.10.0"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "net.kyori.blossom" version "[1,2)"
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.nucleoid.xyz/"
			}
		}
		filter {
			includeGroup "eu.pb4"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.terraformersmc.com/"
			}
		}
		filter {
			includeGroup "com.terraformersmc"
			includeGroup "dev.emi"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
			includeGroup "vazkii.patchouli"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.crystaelix.com/releases/"
			}
		}
		filter {
			includeGroup "thelm.jeidrawables"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.architectury.dev/"
			}
		}
		filter {
			includeGroup "dev.architectury"
			includeGroup "me.shedaniel.cloth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.wispforest.io/"
			}
		}
		filter {
			includeGroup "io.wispforest"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ladysnake.org/releases/"
			}
		}
		filter {
			includeGroup "dev.onyxstudios.cardinal-components-api"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.theepicblock.nl/"
			}
		}
		filter {
			includeGroup "io.github.fablabsmc"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.jamieswhiteshirt.com/libs-release/"
			}
		}
		filter {
			includeGroup "com.jamieswhiteshirt"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.extracraftx.com/"
			}
		}
		filter {
			includeGroup "com.extracraftx.minecraft"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://api.modrinth.com/maven/"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://jitpack.io/"
			}
		}
		filter {
			includeGroup "com.github.DaFuqs"
			includeGroup "com.github.emilyploszaj"
			includeGroup "com.github.devs-immortal"
		}
	}
}

def mcVersion = "1.18.2"
def modName = "SpectrumJEI"
def modId = "spectrumjei"
def specVersion = "18.2"
def vendor = "thelm"

group = "thelm.spectrumjei"
version = "18.2.5"

archivesBaseName = modName

sourceSets {
	main
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	mixin.defaultRefmapName = "${modId}.refmap.json"
	runs {
		configureEach {
			property "fabric.log.console.level", "debug"
		}
		client {
			programArg "--username=Dev"
		}
		server
	}
}

dependencies {
	// Log4j
	implementation "org.apache.logging.log4j:log4j-core:2.24.3"

	// Minecraft
	minecraft "com.mojang:minecraft:1.18.2"
	mappings loom.layered {
		mappings "net.fabricmc:yarn:1.18.2+build.4:v2"
		parchment "org.parchmentmc.data:parchment-1.18.2:2022.11.06@zip"
	}
	modImplementation "net.fabricmc:fabric-loader:0.17.0"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.77.0+1.18.2"
	modImplementation "eu.pb4:placeholder-api:1.1.3+1.17.1"
	modImplementation "com.terraformersmc:modmenu:3.2.5"

	// JEI
	modImplementation("mezz.jei:jei-1.18.2-fabric:10.2.1.1009") {transitive = false}
	include(modImplementation("thelm.jeidrawables:JEIDrawables-Fabric:18.2.4"))

	// Spectrum Included Dependencies
	modImplementation "com.github.DaFuqs:AdditionalEntityAttributes:35d08069"
	modImplementation "com.github.DaFuqs:Arrowhead:5c488c00"
	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-api:4.2.0"
	modImplementation "io.github.fablabsmc:bannerpp:2.0.6-teb.1+mc.1.18.2"
	modImplementation "com.github.emilyploszaj:step-height-entity-attribute:1.0.1"
	modImplementation "com.jamieswhiteshirt:reach-entity-attributes:2.2.0"
	modImplementation("com.github.devs-immortal:Incubus-Core:1.8.4") {transitive = false}
	modImplementation "com.extracraftx.minecraft:ProgrammerArtInjector:1.2.1"

	// Spectrum External Dependencies
	modImplementation "maven.modrinth:revelationary:TTTlCzoW"
	modImplementation "dev.architectury:architectury-fabric:4.12.94"
	modImplementation "me.shedaniel.cloth:cloth-config-fabric:6.5.133"
	implementation "me.zeroeightsix:fiber:0.23.0-2"
	modImplementation "vazkii.patchouli:Patchouli:1.18.2-71.1-FABRIC"
	modImplementation "io.wispforest:owo-lib:0.7.2+1.18"
	modImplementation "dev.emi:trinkets:3.3.1"
	modImplementation "maven.modrinth:dcwa:XXLeEb0H"

	// Spectrum
	modImplementation "maven.modrinth:spectrum:7YmKE57s"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesBaseName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesBaseName
			artifact remapJar
			artifact remapSourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = project.version
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("fabric")
	additionalFiles.from(remapSourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "1258607"
		minecraftVersions.add(mcVersion)
		requires "jei", "spectrum"
		incompatible "roughly-enough-items-hacks"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "8FtYXJhp"
		minecraftVersions.add(mcVersion)
		requires "jei", "spectrum"
		incompatible "roughly-enough-items-hacks"
	}
}
