plugins {
	id "com.crystaelix.loom" version "1.13-SNAPSHOT"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "com.crystaelix.blossom" version "1.3.2"
	id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.crystaelix.com/releases/"
			}
		}
		filter {
			includeGroup "thelm.jeidrawables"
			includeGroup "thelm.fractaljei"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.is-immensely.gay/releases/"
			}
		}
		filter {
			includeGroup "de.dafuqs"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
			}
		}
		filter {
			includeGroup "com.klikli_dev"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.theillusivec4.top/"
			}
		}
		filter {
			includeGroup "top.theillusivec4.curios"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
}

def mcVersion = "1.21.1"
def modName = "SpectrumJEI"
def modId = "spectrumjei"
def specVersion = "21.1"
def vendor = "thelm"

group = "thelm.spectrumjei"
version = "21.1.10+neoforge"

def archivesName = modName
base.archivesName = archivesName

sourceSets {
	main
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	runs {
		configureEach {
			property "forge.logging.console.level", "debug"
		}
		client
		server
	}
}

dependencies {
	// Minecraft
	minecraft "com.mojang:minecraft:1.21.1"
	mappings loom.layered {
		officialMojangMappings()
		parchment "org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip"
	}
	neoForge "net.neoforged:neoforge:21.1.234"

	// JEI
	implementation("mezz.jei:jei-1.21.1-neoforge:19.27.0.346") {transitive = false}
	include(implementation("thelm.jeidrawables:JEIDrawables-NeoForge:21.1.7"))

	// Spectrum Dependencies
	implementation "de.dafuqs:revelationary-neoforge:1.5.0+1.21.1"
	implementation("com.klikli_dev:modonomicon-1.21.1-neoforge:1.120.1") {transitive = false}
	implementation "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1"
	implementation "curse.maven:yeetusexperimentus-635427:5444189"

	// FractalJEI
	include(implementation("thelm.fractaljei:FractalJEI-NeoForge:2.0.2"))

	// Spectrum
	implementation "curse.maven:spectrum-556967:8577000"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesName
			artifact remapJar
			artifact remapSourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = project.version
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("neoforge")
	additionalFiles.from(remapSourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "1258607"
		minecraftVersions.add(mcVersion)
		client = true
		requires "jei", "spectrum"
		incompatible "roughly-enough-items-hacks", "emi"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "8FtYXJhp"
		minecraftVersions.add(mcVersion)
		requires "jei", "spectrum"
		incompatible "roughly-enough-items-hacks", "emi"
	}
}
